/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fogdmzazybivsubwgcfd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvZ2RtemF6eWJpdnN1YndnY2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2NjU2MjgsImV4cCI6MjA5MTI0MTYyOH0.90nCbbCKWiWyestKl_0hkdOzJNXtqYP-2NtalG-VrIA"